Game Development
QSChitanta/Glueksrad pull request #1
Opened 2021-11-05 14:19 UTC by QSChitanta

Coded a game that makes you guess a word, assigned through a random word picker.

2021-11-05 14:39 UTC, JulianBusekros commented on src/de/quinscape/Gluecksrad.java
Methode, die überprüft, ob der User nur einen einzigen Buchstaben eingibt und keine Sonderzeichen/Zahlen wäre hier sinnvoll

2021-11-05 14:39 UTC, JulianBusekros commented on src/de/quinscape/Gluecksrad.java
>      public void loadCurrentCity() {
Du kannst currentCity schon in randomCityGenerator festlegen. Das macht die Methoden loadCurrentCity() und setCurrentCity() überflüssig. Die Liste würde ich auch als Instance Variable festlegen und im Konstruktor füllen. Sonst wird die Liste jedes Mal neu gefüllt

2021-11-05 14:39 UTC, JulianBusekros commented on src/de/quinscape/Gluecksrad.java
> +            if (currentRound == maxTries) {                             //austauschen: if und else if umdrehen
Die if-Bedingungen würde ich eine seperate Methode packen(z.B. isGameOver())

2021-11-05 14:55 UTC, QSChitanta commented on src/de/quinscape/Gluecksrad.java
> +            if (currentRound == maxTries) {                             //austauschen: if und else if umdrehen
Ja, die gesamte roundCounter Methode ist zu groß und muss unbenannt werden. Das ist jetzt mein nächster Schritt

2021-11-05 15:42 UTC, ThorstenClaus requested changes

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    private String currentCity;
Du hast "cities" - wir wollten aber allgemein "Wörter" haben. Bennenne es doch um in "currrentWord"

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    public static LinkedList<String> cityList() {
Name: "wordList"

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +        roundCounter(input);
Ich finde es nicht gut, den scanner als Parameter zu übergeben. 
Erstelle stattdessen eine Methode "getUserCharacter" oder "getUserLetter" die den Scanner aufruft und genau ein Zeichen zurückgibt.

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    public void roundCounter(Scanner input) {
Der Name "roundCounter" ist etwas unglücklich. Was genau passiert in dieser Methode eigentlich? Versuche anhand der Aufgabe einen Namen zu finden. 

Der scanner sollte /muss hier nicht übergeben werden

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +        int maxTries = currentCity.length() * 2;
Sogar das könnte man noch in eine Funktion auslagern: 
int maxTries = calculateMaxTries(currentCity) mit 

```
private int calculateMaxTries(string currentWord) {
return ...
}
```

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +            String userInput = input.nextLine();
Hier die getUserLetter() aufrufen. Wieder eine Funktion, die genau eine kleine Aufgabe übernimmt.

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +            char letter = userInput.toLowerCase().charAt(0);
und diese Zeile kann dann in diese getUserLetter() Funktion rein, so dass genau ein Zeichen zurückgegeben wird.

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    public void checkInput(char letter, boolean[] rightCharGuessed) {
Die Methode macht doch eigentlich so was wie ein update der 'rightCharGuessed" - Liste, oder? 
Passt dann der Name noch?

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    public boolean charGuessing(boolean[] rightCharGuessed) {
Zum Beispiel "isGameWon" ?

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    public void wordOrLinePrinter(boolean[] rightCharGuessed) {
```suggestion
    public void printWord(boolean[] rightCharGuessed) {
```

Vorab an den Anfang stellen. 
Es wird ja immer ein Wort ausgegeben.

2021-11-05 15:42 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +        for (int i = 0; i < currentCity.length(); i++) {
Hier ist das "I" (für Index) wohl OK.

2021-11-08 11:32 UTC, ThorstenClaus requested changes
Ich habe mir das nochmal angesehen. Im Review habe ich dir auch hinweise gegeben, wie du die Benutzer-Eingabe umbauen könntest.

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +        getMaxTries();
Warum machst du das? getMaxTries hat einen Rückgabewert, den du hier nicht nutzt.

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    }
Kann weg.

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +        userInput();
```suggestion
        gameLoop();
```

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    public void gameEngine(Scanner input) {
```suggestion
    public void gameLoop() {
```

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +            char letter = userInput.toLowerCase().charAt(0);
Du brauchst hier eine Funktion, die  genau ein Buchstabe zurückgibt. 
In dieser Funktion (und nur dort) brauchst du den Scanner, die Eingabe nextLine() und du könntest dort auch das chatAt(0) machen.

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +            } else if (isGameWon(rightCharGuessed)) {
Wolltest du nicht erst prüfen, ob das Spiel gewonnen ist, und danach ob die Runden Anzahl verbraucht ist? 
Immerhin könnte der Anwender ja in der letzten Runde das Wort doch noch richtig raten.

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +        return maxTries;
Die Zuweisung brauchst du hier nicht - du kannst sofort retournieren: 
```suggestion
        return currentWord.length() * 2;
```

2021-11-08 11:32 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +    public void wordOrLinePrinter(boolean[] rightCharGuessed) {
entschuldige, ich meinte "Verb (print) an den Anfang stellen". Der Name der Methode wird so einfacher zu lesen: 
printWord()
isGameWon()
getMaxTries()
und so weiter..

2021-11-08 13:35 UTC, merged