Feature/solve word
QSChitanta/Glueksrad pull request #3
Opened 2021-11-11 15:06 UTC by QSChitanta

2021-11-11 16:03 UTC, ThorstenClaus requested changes

2021-11-11 16:03 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +            if (Objects.equals(userInput, player.getCurrentWord())) {
Das ist der Kern. 
Kannst du das noch so machen, dass gross/kleinschreibung ignoriert wird? 
Achtung: benutze NICHT .toLowerCase() ! Gibt es eine andere Möglichkeit, auf Gleichheit eines String zu prüfen und gleichzeitig die gross/kleinschreibung ("case") zu ignorieren?

2021-11-12 11:50 UTC, JulianBusekros approved these changes

2021-11-15 08:41 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +                    player.getCurrentWord().compareToIgnoreCase(userInput))) {
Geht das klarer und kürzer zu kodieren?

2021-11-15 10:04 UTC, ThorstenClaus commented on src/de/quinscape/Gluecksrad.java
> +            if(userInput.equalsIgnoreCase(player.getCurrentWord())){
😀

2021-11-15 10:06 UTC, ThorstenClaus approved these changes

2021-11-15 10:28 UTC, JulianBusekros approved these changes

2021-11-15 10:42 UTC, merged